Program Update
NTUT-kyle/Rotate_Crop_Page pull request #1
Opened 2023-05-19 10:05 UTC by HengWeiBin

2023-05-19 10:52 UTC, NTUT-kyle requested changes
感謝你的修改，提高整體程式，不過 show 出來我不確定會不會影響效能
再請你把建議的地方修改！

Thanks

2023-05-19 10:52 UTC, NTUT-kyle commented on s2_crop_page.py
> +                twoPointDistance((word_result[0][0], word_result[0][1]), (word_result[1][0], word_result[0][1])) - block < 10:
這行可以縮短程式碼：
```python
twoPointDistance(word_result[0], word_result[1]) - block < 10:
```

2023-05-19 12:32 UTC, HengWeiBin commented on s2_crop_page.py
> +                twoPointDistance((word_result[0][0], word_result[0][1]), (word_result[1][0], word_result[0][1])) - block < 10:
你好，
我在commit 10 修改了你要求的内容，`getBoundingBox` 為原本獲得4角的function，已改爲獲取左上右下
main function的修改有忘記push的部分已經補上

整體功能并沒有太大變動，僅增加了顯示切割過程功能、修改算法及修改寫法提高切割速度

### 修改算法如下：
1. s1
   1. 修改找QRCode Function，若原本的方式找不到QRCode，將使用遞迴+縮放的方式重複尋找（意外修改，因爲原本s2有用到，現s2已刪除用此function的程式碼）
2. s2
   1. 刪除尋找稿紙上下的部分
   3. 原本僅使用綠色遮罩來獲取全部字框範圍，改爲尋找綠色遮罩上的矩形内容，並利用找到的正方形增强原本的遮罩
   4. 增加文字自動縮放、質心對齊（寫好才發現助教的網站有自動縮放功能 == ）
   5. 調整對比度，我測是程式用了2份手寫2份電子檔，手寫偶爾還是會遇到找不齊長方形的問題所以加了這功能改善
   6. 使用 Multiprocessing

show 出來執行一定很慢，那是爲了要觀察切割的時候發生了什麽錯誤，一般情況下不應開啓
Multiprocessing 的情況下也不能 show
debug 的時候記得關閉 Multiprocessing，因爲開啓的情況下一但執行，除非關閉終端機，否者不能强制停止

2023-05-19 12:37 UTC, NTUT-kyle requested changes
新增後再通知我，就可以 MERGE 了，我會通知助教你的功勞^^

2023-05-19 12:37 UTC, NTUT-kyle commented on s2_crop_page.py
> +    SHOW = True
[SHOW](https://github.com/NTUT-kyle/Rotate_Crop_Page/pull/1/commits/04a5324d549b7e60203f7530c6699785c4b8b7df#diff-8551486ea40452f581821140e2d8287e604d432fa765e48b8dc3a721bfadbc49R382) 的部分可以加個註解，讓其他人知道其功能！

2023-05-19 13:05 UTC, HengWeiBin commented on s2_crop_page.py
> +    SHOW = True
已修改，show 會在 Multiprocessing 為 True 的時候自動設回 False 所以不用擔心報錯
不確定跟你的新功能有沒有衝突，測試方面麻煩了，謝謝

2023-05-19 15:09 UTC, merged

2023-05-19 16:07 UTC, NTUT-kyle commented
如果有空的話也可以幫我看看新寫的程式 : 
- [find_word_page.py](https://github.com/NTUT-kyle/Rotate_Crop_Page/blob/main/find_word_page.py) 是用於用 Unicode 尋找 Page 編號的
- [manual_cutting.py](https://github.com/NTUT-kyle/Rotate_Crop_Page/blob/main/manual_cutting.py) 是用於手動切割的(這部分應該蠻多可以改進的@@)

2023-05-20 04:29 UTC, HengWeiBin commented
> * [manual_cutting.py](https://github.com/NTUT-kyle/Rotate_Crop_Page/blob/main/manual_cutting.py) 


你的 getTLTRBLBR 被我改成 getBoundingBox（左上右下） 了，所以會報錯